### ISSUE TITLE
Configurable sysctl values?

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#123]
Support configuring values like `net.core.somaxconn` which are not directly inherited from the host.

**Comment by mjacksonw** [comment]
Just a ping on this, since we're running up against it hard again. Thoughts, just to be annoying:
1. Perhaps mount `/proc` as a volume (renamed so docker doesn't set it read-only):

```
docker run ... -v /proc:/proc-rw ...
```

So then you'd be able to `echo 1024 > /proc-rw/sys/net/core/somaxconn` to your heart's content.
1. Does it even need to be configurable? Would there be much downside to setting `net.core.somaxconn` to something significantly higher, like `16384` or `32768`? Seems any web stack is liable to run up against that default value of `128` sooner or later, and many (most?) app servers make it relatively easy to limit the impact value at that level.

**Comment by fancyremarker** [comment]
@mjacksonw: I'll research/experiment with Option 1 to make sure there are no blockers to that approach. I think Option 2 would work as well. We'd just need to implement it by including a value for `somaxconn` with each `docker run` we invoke, since:
- Docker containers don't inherit the host's value for `net.core.somaxconn`
- There's no way to configure a new default (at the daemon level) for the value of `somaxconn` that Docker uses when launching containers.
