### ISSUE TITLE
Error: "fatal: revision walk setup failed" on git push

### ISSUE THREAD

**Issue by fancyremarker** [aptible/support#183]

**Comment by wmadden** [comment]
We're seeing this in one of our repos too

**Comment by krallin** [comment]
This issue is caused by pushing to Aptible from a shallow clone (i.e. a repository that doesn't have all the history of your project). Shallow clones are typically used by CI platforms to optimize build speed.

To solve the problem, you simply need to "unshallow" your repository before pushing it. The best way to do so is right before pushing to Aptible (so that you only spend time unshallowing your repository if you're actually going to deploy to Aptible).

This can be done like so:

```
# Some build instructions
git fetch --unshallow || true      # This is new
git push aptible master            # You already have this
```

Cheers,
